import type { ThemeDefinition } from 'vuetify'
import { tokens } from '@/design-tokens/tokens'

const { brand, neutral, semantic, light, dark } = tokens.color

export const staticPrimaryColor = brand.primary
export const staticPrimaryDarkenColor = brand.primaryDarken

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': brand.primaryDarken,
      'secondary': brand.secondary,
      'secondary-darken-1': brand.secondaryDarken,
      'on-secondary': '#fff',
      'success': semantic.success,
      'success-darken-1': '#4DB600',
      'on-success': '#fff',
      'info': semantic.info,
      'info-darken-1': '#149FE6',
      'on-info': '#fff',
      'warning': semantic.warning,
      'warning-darken-1': '#E6A200',
      'on-warning': '#fff',
      'error': semantic.error,
      'error-darken-1': '#E64449',
      'on-error': '#fff',
      'background': light.background,
      'on-background': light.text,
      'surface': light.surface,
      'on-surface': light.text,
      'grey-50': neutral[50],
      'grey-100': neutral[100],
      'grey-200': neutral[200],
      'grey-300': neutral[300],
      'grey-400': neutral[400],
      'grey-500': neutral[500],
      'grey-600': neutral[600],
      'grey-700': neutral[700],
      'grey-800': neutral[800],
      'grey-900': neutral[900],
      'perfect-scrollbar-thumb': light.border,
      'skin-bordered-background': light.surface,
      'skin-bordered-surface': light.surface,
      'expansion-panel-text-custom-bg': light.surfaceMuted,
      'track-bg': light.track,
      'chat-bg': light.surfaceMuted,
    },

    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': light.text,
      'tooltip-background': '#1A0E33',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': light.text,
      'border-opacity': 0.12,
      'table-header-color': '#F6F7FB',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 shadows
      'shadow-key-umbra-color': light.text,
      'shadow-xs-opacity': '0.16',
      'shadow-sm-opacity': '0.18',
      'shadow-md-opacity': '0.20',
      'shadow-lg-opacity': '0.22',
      'shadow-xl-opacity': '0.24',
    },
  },

  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': brand.primaryDarken,
      'secondary': brand.secondary,
      'secondary-darken-1': brand.secondaryDarken,
      'on-secondary': '#fff',
      'success': semantic.success,
      'success-darken-1': '#4DB600',
      'on-success': '#fff',
      'info': semantic.info,
      'info-darken-1': '#149FE6',
      'on-info': '#fff',
      'warning': semantic.warning,
      'warning-darken-1': '#E6A200',
      'on-warning': '#fff',
      'error': semantic.error,
      'error-darken-1': '#E64449',
      'on-error': '#fff',
      'background': dark.background,
      'on-background': dark.text,
      'surface': dark.surface,
      'on-surface': dark.text,
      'grey-50': '#2A2E42',
      'grey-100': '#2F3349',
      'grey-200': dark.border,
      'grey-300': '#5E6692',
      'grey-400': '#7983BB',
      'grey-500': '#8692D0',
      'grey-600': '#AAB3DE',
      'grey-700': dark.textMuted,
      'grey-800': '#CFD3EC',
      'grey-900': '#E7E9F6',
      'perfect-scrollbar-thumb': dark.border,
      'skin-bordered-background': dark.surface,
      'skin-bordered-surface': dark.surface,
      'expansion-panel-text-custom-bg': '#373350',
      'track-bg': dark.track,
      'chat-bg': dark.surfaceMuted,
    },

    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': dark.surface,
      'tooltip-background': '#F7F4FF',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'disabled-opacity': 0.4,
      'dragged-opacity': 0.1,
      'border-color': dark.text,
      'border-opacity': 0.12,
      'table-header-color': '#3D3759',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 Shadows
      'shadow-key-umbra-color': '#131120',
      'shadow-xs-opacity': '0.20',
      'shadow-sm-opacity': '0.22',
      'shadow-md-opacity': '0.24',
      'shadow-lg-opacity': '0.26',
      'shadow-xl-opacity': '0.28',
    },
  },
}

export default themes
